services:
  mongo:
    image: mongo:latest
    container_name: ${appName}_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  spring_service:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    container_name: ${appName}_app
    ports:
      - "8080:8080"
      - "35729:35729"
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}

    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./mvnw:/app/mvnw
      - ./.mvn:/app/.mvn
      - ./.env:/app/.env

volumes:
  mongo_data:
    driver: local
  src:
    driver: local
