apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spring-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-spring-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-spring-app
    spec:
      containers:
        - name: spring-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://{{ .Release.Name }}-mongodb:27017/{{ .Values.mongodb.database }}"
