apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  type: {{ .Values.mongodbService.type }}
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: {{ .Release.Name }}-mongodb